### ISSUE TITLE
not finding facebook cookies

### ISSUE THREAD

**Issue by Maslor** [diogomonica/py-cookieJsInjection#2]
I'm running cookieJsInjection.py on ubuntu with the -facebook flag (over wlan0) but it doesn't print any facebook cookies. It does print other cookies when running without the flag.

**Comment by diogomonica** [comment]
Hi there. Facebook now uses HTTPS for all of their communications (including the use of HSTS headers to protect against SSLStrip, etc).

This tool no longer works for sniffing facebook cookies.

**Comment by Maslor** [comment]
You're right, thanks!
